fixtures:
  repositories:
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt"
      branch: "4.0.0"
  forge_modules:
    motd: "puppetlabs/motd"
    ntp: "puppetlabs/ntp"
    stdlib: "puppetlabs/stdlib"
    ruby: "puppetlabs/ruby"
    gcc: "puppetlabs/gcc"
    inifile: "puppetlabs/inifile"
    vcsrepo: "puppetlabs/vcsrepo"
    git: "puppetlabs/git"
    make: "puppet/make"
    r10k: "puppet/r10k"
    gitlab: "vshn-gitlab"
    docker: "garethr/docker"

  symlinks:
    "profile": "#{source_dir}/site/profile"
