---
sudo: false
cache: bundler
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake test"
matrix:
    fast_finish: true
    include:
    - rvm: 2.4.0
      env: PUPPET_GEM_VERSION="~> 4.0"
    - rvm: default
      sudo: required
      services: docker
      env:
        - BEAKER_debug=1
        - PUPPET_INSTALL_TYPE=agent
      script: bundle exec rake beaker
notifications:
  email: false
