---
sudo: false
cache: bundler
language: ruby
bundler_args: --without system_tests
script: "cd site/profile && bundle exec rake test"
rvm:
  - 2.4.0
env: PUPPET_GEM_VERSION="~> 4.0"
notifications:
  email: false
